--liquibase formatted sq
--changeset marat:1
create table if not exists users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(30),
    password    text,
    first_name  varchar(30),
    last_name   varchar(40),
    phone       varchar(12),
    email       varchar(40),
    role        varchar(5),
    image       text);
